apiVersion: v1
kind: ConfigMap
metadata:
  name: trains-service-config
data:
  # Замените на DNS сервисов из вашего кластера / общего Helm chart
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.messaging.svc.cluster.local:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka/"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
