apiVersion: v1
kind: Service
metadata:
  name: trains-service
spec:
  type: ClusterIP
  selector:
    app: trains-service
  ports:
    - name: http
      port: 8035
      targetPort: http
      protocol: TCP
